config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, :except => [:destroy, :edit, :update] do
    member do 
      # como hago esto a mano???????????
      resources :reviews, only: [:new, :create] 
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: (0..5).to_a }, numericality: {only_integer: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  
  def index
    @restaurants = Restaurant.all
  end
  
  def new
    @restaurant = Restaurant.new
    @states = ["chinese", "italian", "japanese", "french", "belgian"]
  end

  def create
    restaurant = Restaurant.new(restaurants_params)
    if restaurant.valid?
      restaurant.save
      redirect_to restaurant_path(restaurant), notice: 'Restaurant was successfully created.'
    else
      render new_restaurant_path
    end
  end

  def show
    @reviews = Review.joins(:restaurant).where(restaurant_id: params[:id])
  end
  
  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end  

  def restaurants_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = Restaurant.find(params[:id])
    if @review.valid?
      @review.save
      redirect_to restaurant_path(@review.restaurant)
    else
      redirect_to restaurants_path
    end
  end
  
  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
  <div class="container d-flex justify-content-between" style="margin-top: 30px; margin-bottom: 10px">
    <%= link_to "Back to index", restaurants_path, class: "btn btn-primary" %>
    <%= link_to "Create new restaurant", new_restaurant_path, class: "btn btn-outline-secondary" %>
  </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants <strong>list</strong></h1>

<ul class="list-group">
  <% @restaurants.each do |restaurant| %>
    <li class="list-group-item "><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>Creating a new restaurant</h1>

<%= form_for(@restaurant, html: {class: "form-group"}) do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, class: "form-control" %>

    <%= f.label :address, "Address" %>
    <%= f.text_field :address, class: "form-control" %>

    <%= f.label :category, "category" %>
    <%= f.select :category, @states, class: "form-control" %>

    <%= f.submit "Save" %>
<% end %>
  

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<ul class="list-group list-group-flush">
  <li class="list-group-item"><strong>Address: </strong><%= @restaurant.address %></li>
  <li class="list-group-item"><strong>Phone number: </strong><%= @restaurant.phone_number %></li>
  <li class="list-group-item"><strong>Category food: </strong><%= @restaurant.category %></li>
</ul>
<br>
<br>
<h2>Reviews</h2>
<ul class="list-group list-group-flush">
  <% @reviews.each do |review| %>
    <li class="list-group-item">
    <div class="d-flex justify-content-between">
      <p><%= review.content %></p>
      <p><strong> <%= review.rating %> </strong></p>
    </div>
    </li>
  <% end %>
</ul>



<%= link_to "New review" , new_review_path, class: 'btn btn-secondary mt-3' %>

app/views/reviews/new.html.erb
<h1>Holis</h1>

<%= form_for(@review, html: {class: "form-group"}) do |f| %>
    <%= f.label :rating, "rating" %>
    <%= f.text_field :rating, class: "form-control" %>

    <%= f.label :content, "content" %>
    <%= f.text_field :content, class: "form-control" %>

    <%= f.submit "Submit", class: "mt-3" %>
<% end %>
  